version: '3.9'

services:
  webapp:
    container_name: controle_contatos-app
    build: .
    networks:
      webapp-bridge:
        ipv4_address: 172.25.0.10
    volumes:
      - .:/source
    environment:
      - ASPNETCORE_URLS=http://localhost;http://172.25.0.10
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - Infra/mysql.env
      - Infra/dev.env
    depends_on:
      - mysql_db

  mysql_db:
    container_name: controle_contatos-db
    image: mysql:8
    ports:
      - '3306:3306'
    networks:
      webapp-bridge:
        ipv4_address: 172.25.0.12
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-database:/docker-entrypoint-initdb.d
    env_file:
      - Infra/mysql.env
    restart: on-failure:5

  myAdmin:
    container_name: controle_contatos-php_my_admin
    image: phpmyadmin:5.2.1
    ports:
      - 8081:8081
    networks:
      webapp-bridge:
        ipv4_address: 172.25.0.11
    links:
      - mysql_db
    environment:
      PMA_HOST: 'mysql_db'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

    depends_on:
      - mysql_db

#To use volumes instead folder inside the project root
volumes:
  mysql-data:


networks:
  webapp-bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
